### ISSUE TITLE
Return `GitHub Name (@github-handle)` in list of contributors

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/whats-new-in-emberland#39]
This is a nice to have that would match the Ember Times "style guide"

**Comment by abhilashlr** [comment]
This might require an additional API request for each contributor because the "Search issues & PR" API doesn't receive more info about a user. Did a quick ember inspect on the ember-data tab and see that the user's names are all undefined. I believe this would add to the API rate limiting if we fetch a user's detail again.

Thoughts?
