### ISSUE TITLE
Consider going back to random sorting order

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/whats-new-in-emberland#46]
Now that we are adding the name with the handle, alphabetical by handle doesn't make as much sense

Having an "A" name, I am a bit more sensitive to this, it seems weird to see my name first every week, as a writer of the newsletter. I think the previous "random" order will allow folks to be recognized more, sometimes a random contributor is even first in the list! And I guess it's a bit more "fun"?

But this is just an opinion, happy to run it by the team / share context of the rants and raves of this list! 

I am jotting this down post-goodbitsing so I don't forget and added it to https://github.com/orgs/ember-learn/projects/18

**Comment by ijlee2** [comment]
@amyrlam @abhilashlr I was wondering how much you want the feature of random order. If you think that a random order would be must-have, we can create a Hacktoberfest issue. If it's more nice-to-have, maybe we can close this issue?

Randomizing the order of contributors would require a change in how we [test a pull request](https://github.com/ember-learn/whats-new-in-emberland/blob/master/tests/acceptance/pull-requests-test.js#L64-L92). Rather than finding a pull request by the array index, I think we would update the test selector to add metadata (e.g. `data-test-pull-request="<PR title>"`) so that we can find the pull request by the title.

A random order would also cause issue with Percy, which I'd like to install now that we have mock data from Mirage. We could add a conditional logic to the `pull-requests` controller (if the environment is `test`, don't randomize), but it does add a bit of noise in the controller.

**Comment by amyrlam** [comment]
i would like to bring the feature back. since this is an internal tool, we don't _have_ to have testing. 

* if the issue is testing, it can be an option (as is - regular order), click a button that we don't test - random order? 
* for percy, we can hide the section: https://docs.percy.io/docs/percy-specific-css#hiding-regions-with-percy-specific-css

**Comment by ijlee2** [comment]
@amyrlam Yep, sounds good!

The first option reminded me that if we take the snapshot of `pull-requests` page without clicking on the `Get Contributors List` button, we would get the same snapshot every time.

Since there are a few strategies that we can take for Percy, let's go ahead with making the issue a Hacktoberfest one.

**Comment by ijlee2** [comment]
Let me close this issue in favor of #58 .

**Comment by amyrlam** [comment]
@ijlee2 cool, sounds good! thanks for setting up an issue for hacktoberfest!
